language: clojure

lein: lein2

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - echo "hello stdin" | lein2 run | tee lein-run.txt
  - echo "hello stdin" | lein2 trampoline run | tee lein-trampoline-run.txt
  - diff lein-run.txt lein-trampoline-run.txt
